HOST = '0.0.0.0'
PORT = '80'

ACCESS_LOG = 'access.log'
ERROR_LOG = 'error.log'
DEBUG_LOG = 'debug.log'

DEBUG = False

SECRET_KEY_FILE = 'jwt.pri'
SECRET_KEY_FILE_MODE = 0o600
PUBLIC_KEY_FILE = 'jwt.pub'
PUBLIC_KEY_MODE = 0o666

SALT_FILE = 'starstudio.salt'
SALT_FILE_MODE = 0o600

MYSQL_DATABASE_HOST = 'localhost'
MYSQL_DATABASE_PORT = 3306
MYSQL_DATABASE_USER = 'root'
MYSQL_DATABASE_PASSWORD = None
MYSQL_DATABASE_DB = 'starstudio'
MYSQL_DATABASE_CHARSET = 'utf8'

ACCESS_LOG = 'access.api.log'
ERROR_LOG = 'error.api.log'

LAN_DEV_REDIS_HOST = ''
LAN_DEV_REDIS_PORT = ''
LAN_DEV_REDIS_PROBER_IDENT_PREFIX = 'LANDEV_DEFAULT'

LAN_DEV_LIVENESS_TRACK_INTERVAL = 5
LAN_DEV_LIVENESS_PROBE_TIMEOUT = 5
LAN_DEV_LIVENESS_PROBE_INTERVAL = 20
LAN_DEV_INTERFACE = 'wlp3s0'
