version: "3.2"

services:
    account_storage:
        image: mysql:8.0.12
        environment:
          - MYSQL_ROOT_PASSWORD=your_password
          - MYSQL_DATABASE=your_database
        volumes:
          - type: bind
            source: ./member.sql
            target: /docker-entrypoint-initdb.d/init.sql
          - type: bind
            source: ./docker-data/mysql/data
            target: /var/lib/mysql


    redis:
        image: redis:5.0.0
        volumes:
          - type: bind
            source: ./docker-data/redis/data
            target: /data/
            

    api-server:
        build:
            context: ./
            dockerfile: ./Docker/apiserver/Dockerfile
            args:
            - DIST_VERSION=1.0.2
        image: starsso:1.0.2
        environment: 
          - SSO_MYSQL_HOST=account_storage
          - SSO_MYSQL_PASSWORD=your_password
          - SSO_MYSQL_DB=your_database
          - SSO_MYSQL_USER=root
          - SSO_REDIS_HOST=redis
          - SSO_API_HOST=http://sso.test.com
        ports:
          - "8000:80"
        depends_on:
          - account_storage
          - redis
        volumes:
          - type: bind
            source: ./docker-data/StarSSO/conf
            target: /etc/starsso
          - type: bind
            source: ./docker-data/StarSSO/log
            target: /var/log/starsso
            

    #checkbot:
    #    image: checkbot:1.0.1
    #    environment:
    #      - REDIS_HOST=publish-redis
    #      - MYSQL_HOST=account_storage
    #      - MYSQL_PASSWORD=your_password
    #      - MYSQL_DB=starstudio
    #      - MYSQL_USER=root
