FROM python:3.6.6-alpine3.7

ARG DIST_VERSION
ARG LANDEV_VERSION

RUN set -xe;\
    sed -Ei "s/dl-cdn\.alpinelinux\.org/mirrors.tuna.tsinghua.edu.cn/g" /etc/apk/repositories; \
    mkdir /apk-cache; \
    apk add supervisor gettext tzdata py-cffi bash libffi-dev openssl-dev musl-dev --cache-dir /apk-cache; \
    rm -rf /apk-cache; \
    rm /etc/localtime; \
    ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
    

COPY ./dist/CheckBot.tar.gz /docker-build/
COPY ./dist/LANDevice.tar.gz /docker-build/

RUN set -xe;\
    echo [easy_install] >> ~/.pydistutils.cfg ;\
    echo index-url=https://pypi.tuna.tsinghua.edu.cn/simple >> ~/.pydistutils.cfg; \
    mkdir /apk-cache; \
    apk add gcc g++ linux-headers --cache-dir /apk-cache -t build-deps; \
    cd /docker-build; \
    tar -xvzf LANDevice.tar.gz ;\
    cd LANDevice-$LANDEV_VERSION;\
    python ./setup-landevice.py install; \
    cd ..;\
    tar -xvzf CheckBot.tar.gz ;\
    cd CheckBot-$DIST_VERSION;\
    python ./setup-checkbot.py install; \
    apk del build-deps; \
    rm -rf /apk-cache; \
    rm -rf /docker-build; \
    mkdir /etc/CheckBot

COPY ./Docker/conf-checkbot/* /data/
COPY ./Docker/Entrypoint-CheckBot.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
